import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { readFileSync } from 'node:fs';
import { DatabaseSync,type SQLInputValue } from 'node:sqlite';
import solc from 'solc';
import { createPublicClient,createWalletClient,http,erc20Abi,bytesToHex,parseAbi,keccak256,stringToHex,type Hex } from 'viem';
import { monadTestnet } from 'viem/chains';
import { mnemonicToAccount } from 'viem/accounts';
import { taskManagerAbi } from '@agent-task/contracts';
import { resolveAgent, verifyWorkerBinding } from '@agent-task/identity';
import { hashJson } from '@agent-task/protocol/json';
import { ToolPayments,type ToolRequest } from '../apps/object-store/src/tool-payments.js';
import { mppService } from '../apps/object-store/src/mpp-service.js';
import { makeTask,taskParams,type PlatformConfig,type PlatformGoal } from '../apps/object-store/src/platform-domain.js';
import { verifyPlatformResult } from '../apps/object-store/src/platform-execution.js';
import type { Env } from '../apps/object-store/src/index.js';
import { deliveryPrivateKey,deliveryPublicKey,deliverySalt,deliveryContext,openJson,verifiedOpening } from '@agent-task/privacy';
import { protectResult,reviewResult } from '../apps/object-store/src/private-deliveries.js';
import { validateResultManifest } from '@agent-task/protocol';
import { takerApi, getRun, storeTakerExecution } from '../apps/object-store/src/taker-api.js';
import { TakerClient } from '../packages/taker/src/client.js';

test('real Monad-EVM MPP payment recovers lost response without paying twice and delivery is independently verified',{timeout:120000},async()=>{
 const listener=createServer();await new Promise<void>(r=>listener.listen(0,'127.0.0.1',r));const port=(listener.address() as {port:number}).port;await new Promise<void>(r=>listener.close(()=>r()));
 const node=spawn('.tools/foundry/anvil',['--network','monad','--hardfork','MonadNine','--chain-id','10143','--port',String(port),'--silent'],{stdio:'ignore'});
 const rpc=`http://127.0.0.1:${port}`,nativeFetch=globalThis.fetch;
 const client=createPublicClient({chain:monadTestnet,transport:http(rpc),pollingInterval:50});
 const accounts=Array.from({length:7},(_,addressIndex)=>mnemonicToAccount('test test test test test test test test test test test junk',{addressIndex}));
 const wallets=accounts.map(account=>createWalletClient({chain:monadTestnet,account,transport:http(rpc)}));
 const db=new DatabaseSync(':memory:');db.exec(readFileSync('apps/object-store/schema.sql','utf8'));db.exec(readFileSync('apps/object-store/platform-schema.sql','utf8'));
 try {
  for(let i=0;;i++){try{await client.getChainId();break;}catch{if(i>40)throw new Error('anvil startup');await new Promise(r=>setTimeout(r,100));}}
  const receipt=async(hash:Hex)=>{const value=await client.waitForTransactionReceipt({hash});assert.equal(value.status,'success');return value;};
  async function deploy(name:string,args:unknown[]=[]){const artifact=JSON.parse(readFileSync(`contracts/out/${name}.sol/${name}.json`,'utf8'));return(await receipt(await wallets[0]!.deployContract({abi:artifact.abi,bytecode:artifact.bytecode.object,args}))).contractAddress!;}
  const token=await deploy('MockUSDC'),manager=await deploy('TaskManager',[token,[accounts[0]!.address],1]);
  // ABI fixture only: this test does not claim to validate the ERC-8004 implementation itself.
  const compiled=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'Registry.sol':{content:'pragma solidity 0.8.37; contract Registry { address public wallet; address public originalOwner; string public uri; constructor(address w,string memory u){wallet=w;originalOwner=w;uri=u;} function ownerOf(uint256) external view returns(address){return originalOwner;} function tokenURI(uint256) external view returns(string memory){return uri;} function getAgentWallet(uint256) external view returns(address){return wallet;} function clearWallet() external{wallet=address(0);} }'}},settings:{outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));
  const artifact=compiled.contracts['Registry.sol'].Registry;
  const registry=(await receipt(await wallets[0]!.deployContract({abi:artifact.abi,bytecode:`0x${artifact.evm.bytecode.object}`,args:[accounts[5]!.address,'https://provider.test/services/agent.json']}))).contractAddress!;
  const config:PlatformConfig={chainId:10143,token,manager,factory:manager,operator:accounts[1]!.address,worker:accounts[2]!.address,sponsor:accounts[0]!.address,rpcUrl:'https://tool-rpc.test',storageUrl:'https://platform.test'};
  const ref={chainId:'10143',registry,agentId:'1'};
  const env:Env={PLATFORM_CONFIG:JSON.stringify(config),MPP_TOOL_CONFIG:JSON.stringify({endpoint:'https://provider.test/services/transfers',provider:ref,maxPerCall:'1000',maxPerTask:'2000',maxPerDay:'10000',maxGasWei:'1000000000000000000'}),MPP_PAYER_KEY:bytesToHex(accounts[4]!.getHdKey().privateKey!),MPP_SERVICE_CONFIG:JSON.stringify({agent:ref,recipient:accounts[5]!.address,priceBaseUnits:'1000',origin:'https://provider.test'}),MPP_SERVICE_SECRET:'fixture-only-challenge-secret-at-least-32-bytes',DB:{prepare(sql){let values:SQLInputValue[]=[];return{bind(...v){values=v as SQLInputValue[];return this;},async first<T>(){return(db.prepare(sql).get(...values)??null) as T|null;},async run(){return db.prepare(sql).run(...values);}};}}};
  let paidResponses=0,loseResponse=true;let paidRequest:Request|undefined;let revokeOnQuote:string|undefined;
  globalThis.fetch=async(input,init)=>{
    const url=String(input);
    if(url.startsWith('https://tool-rpc.test')){const body=JSON.parse(String(init?.body));if(body.method==='eth_getBlockByNumber'&&body.params[0]==='finalized')body.params[0]='latest';if(body.method==='eth_call'&&body.params[1]==='finalized')body.params[1]='latest';return nativeFetch(rpc,{...init,body:JSON.stringify(body)});}
    if(url.startsWith('https://provider.test/')){if(new Headers(init?.headers).has('authorization'))paidRequest=new Request(url,init);const r=await mppService(new Request(url,init),env);if(r.status===402&&revokeOnQuote){db.prepare('UPDATE platform_executors SET revoked=1 WHERE id=?').run(revokeOnQuote);revokeOnQuote=undefined;}if(r.ok&&new Headers(init?.headers).has('authorization')){paidResponses++;if(loseResponse){loseResponse=false;throw new Error('lost paid response');}}return r;}
    if(url.startsWith('https://platform.test/platform/taker/'))return takerApi(new Request(url,init),env);
    return nativeFetch(input,init);
  };
  const mintAbi=parseAbi(['function mint(address,uint256)']);
  for(const i of [3,4])await receipt(await wallets[0]!.writeContract({address:token,abi:mintAbi,functionName:'mint',args:[accounts[i]!.address,1000000n]}));
  const head=await client.getBlock();
  const goal:PlatformGoal={id:crypto.randomUUID(),owner:accounts[3]!.address.toLowerCase() as Hex,vault:accounts[3]!.address,input:{id:crypto.randomUUID(),goal:'MPP 本地真实转账与独立复算测试',kind:'analysis',execution:'platform',reward:'50000',fromBlock:'1',toBlock:String(head.number)},createdAt:new Date().toISOString(),status:'running'};
  const deliveryKey=deliveryPrivateKey(new Uint8Array(32).fill(7)),reviewKey=new Uint8Array(32).fill(8);
  env.DELIVERY_REVIEW_KEY=bytesToHex(reviewKey);
  goal.input.delivery={scheme:'worknet-delivery/1',salt:deliverySalt('platform.test',goal.owner,goal.id),publicKey:deliveryPublicKey(deliveryKey),reviewPublicKey:deliveryPublicKey(reviewKey),rpId:'platform.test'};
  const spec=makeTask(goal,config,Number(head.timestamp),head.number);goal.spec=spec;
  await receipt(await wallets[3]!.writeContract({address:token,abi:erc20Abi,functionName:'approve',args:[manager,50000n]}));
  await receipt(await wallets[3]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'createTask',args:[hashJson('request'),config.operator,taskParams(spec,config.storageUrl)]}));
  await receipt(await wallets[2]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'claimTask',args:[1n]}));
  goal.taskId='1';db.prepare('INSERT INTO platform_goals(id,owner,body,active,updated_at) VALUES (?,?,?,1,?)').run(goal.id,goal.owner,JSON.stringify(goal),Date.now());
  const memory=new Map<string,unknown>();const context={storage:{async get(k:string){return structuredClone(memory.get(k));},async put(k:string|Record<string,unknown>,v?:unknown){if(typeof k==='string')memory.set(k,structuredClone(v));else for(const[key,value]of Object.entries(k))memory.set(key,structuredClone(value));},async delete(k:string){memory.delete(k);}}};
  let actor=new ToolPayments(context as any,env);
  const input:ToolRequest={owner:goal.owner,taskId:'1',attempt:'1',specHash:hashJson(spec),input:spec.input as ToolRequest['input']};
  const call=()=>actor.fetch(new Request('https://internal/purchase',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}));
  const first=await call();assert.equal(first.status,503,await first.text());
  assert.equal(await client.readContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[accounts[5]!.address]}),1000n,'payment happened before response loss');
  actor=new ToolPayments(context as any,env);
  const second=await call();const result=await second.json() as any;assert.equal(second.status,200,JSON.stringify(result));
  const concurrent=await Promise.all([call(),call()]);assert(concurrent.every(r=>r.ok));
  assert.equal(await client.readContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[accounts[5]!.address]}),1000n);
  assert.equal(paidResponses,2,'retry recovers provider cache; completed actor cache avoids more calls');
  const stolen=paidRequest!.clone();const stolenHeaders=new Headers(stolen.headers);stolenHeaders.delete('x-worknet-payment-proof');
  assert.equal((await mppService(new Request(stolen.url,{method:'POST',headers:stolenHeaders,body:await stolen.text()}),env)).status,403,'a public transaction hash alone cannot redeem another payer purchase');
  const swapped=paidRequest!.clone();const swappedHeaders=new Headers(swapped.headers);swappedHeaders.set('idempotency-key',hashJson('other-order'));
  assert.equal((await mppService(new Request(swapped.url,{method:'POST',headers:swappedHeaders,body:await swapped.text()}),env)).status,403,'payment ownership proof is bound to the original order');
  assert.equal(db.prepare('SELECT count(*) n FROM tool_service_orders').get()!.n,1);
  const evidence=db.prepare('SELECT body FROM objects WHERE hash=?').get(result.artifact.hash)!.body as string;
  assert(!evidence.includes('raw'));assert(!evidence.includes(env.MPP_PAYER_KEY!));assert(evidence.includes('worknet-tool-purchase/1'));
  assert.equal((await verifyPlatformResult(spec,result,config,env)).verdict,'accept');
  assert.equal((await verifyPlatformResult(spec,{...result,output:{...result.output,eventCount:String(BigInt(result.output.eventCount)+1n)}},config,env)).verdict,'reject');
  const manifest=await protectResult(env,spec,validateResultManifest({protocol:'agent-task/0.1',settlementChainId:'10143',taskManager:manager.toLowerCase(),taskId:'1',attempt:'1',worker:config.worker.toLowerCase(),specHash:hashJson(spec),output:result.output,provenance:result.provenance,artifacts:[result.artifact]}));
  const encryptedHash=hashJson(manifest);
  await receipt(await wallets[2]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'submitResult',args:[1n,1n,encryptedHash,`${config.storageUrl}/objects/${encryptedHash}`]}));
  assert.equal((await verifyPlatformResult(spec,await reviewResult(env,manifest,spec),config,env)).verdict,'accept');
  await assert.rejects(reviewResult(env,{...manifest,output:result.output},spec),/PRIVATE_RESULT_BINDING/);
  const opening=await openJson((manifest.output as any).envelope,deliveryKey,deliveryContext(manifest));
  assert.deepEqual(verifiedOpening(manifest.output,opening),result.output);deliveryKey.fill(0);
  await receipt(await wallets[3]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'acceptResult',args:[1n,1n,encryptedHash]}));
  assert.equal(await client.readContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[config.worker]}),50000n,'worker receives the full task reward; platform pays tool costs separately');
  assert.equal((await client.readContract({address:manager,abi:taskManagerAbi,functionName:'getTask',args:[1n]})).status,3);
  // A separately paired external worker buys the fixed task input through the public API.
  env.PLATFORM={} as any;
  env.TOOL_PAYMENTS={idFromName:()=>1,get:()=>({fetch:(url:string,init:RequestInit)=>actor.fetch(new Request(url,init))})} as any;
  const external=accounts[6]!.address.toLowerCase() as Hex,executorId=crypto.randomUUID(),otherId=crypto.randomUUID(),runId=crypto.randomUUID();
  const tokenA='aa'.repeat(32),tokenB='bb'.repeat(32);
  for(const [id,credential] of [[executorId,tokenA],[otherId,tokenB]])db.prepare('INSERT INTO platform_executors(id,token_hash,name,owner,approved,revoked,expires_at,created_at) VALUES (?,?,?,?,1,0,?,?)').run(id!,keccak256(stringToHex(credential!)),'test executor',external,Date.now()+600000,Date.now());
  const externalGoal:PlatformGoal={...goal,id:crypto.randomUUID(),taskId:'2',input:{...goal.input,execution:'market'}};delete externalGoal.input.delivery;
  const nextHead=await client.getBlock();externalGoal.spec=makeTask(externalGoal,config,Number(nextHead.timestamp),nextHead.number);
  const externalSpec=externalGoal.spec;
  await receipt(await wallets[3]!.writeContract({address:token,abi:erc20Abi,functionName:'approve',args:[manager,50000n]}));
  await receipt(await wallets[3]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'createTask',args:[externalSpec.clientRequestId as Hex,config.operator,taskParams(externalSpec,config.storageUrl)]}));
  db.prepare('INSERT INTO platform_goals(id,owner,body,active,updated_at) VALUES (?,?,?,1,?)').run(externalGoal.id,externalGoal.owner,JSON.stringify(externalGoal),Date.now());
  const grant={authorized:true,validUntil:Number(nextHead.timestamp)+600,specHash:hashJson(externalSpec),spec:externalSpec,mode:'wallet'};
  db.prepare('INSERT INTO platform_runs(id,owner,executor_id,task_id,attempt,body,created_at) VALUES (?,?,?,\'2\',\'1\',?,?)').run(runId,external,executorId,JSON.stringify(grant),Date.now());
  const externalClient=new TakerClient('https://platform.test',tokenA),wrongClient=new TakerClient('https://platform.test',tokenB);
  await assert.rejects(wrongClient.purchaseTransfers(runId),/NOT_FOUND/);
  await assert.rejects(externalClient.purchaseTransfers(runId),/MPP_TASK_INACTIVE/,'unclaimed tasks cannot spend');
  await receipt(await wallets[6]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'claimTask',args:[2n]}));
  await assert.rejects(externalClient.request(`/runs/${runId}/tools/transfers`,{endpoint:'https://attacker.test',amount:'99999'}),/INVALID_INPUT/);
  const externalInput={owner:external,taskId:'2',attempt:'1',runId,executorId:otherId,specHash:hashJson(externalSpec),input:externalSpec.input};
  const wrongActor=await actor.fetch(new Request('https://internal/purchase',{method:'POST',body:JSON.stringify(externalInput)}));assert.equal(wrongActor.status,503,'actor independently rejects swapped executor');
  const payerNonce=await client.getTransactionCount({address:accounts[4]!.address});
  revokeOnQuote=executorId;
  await assert.rejects(externalClient.purchaseTransfers(runId),/MPP_EXECUTOR_INACTIVE/,'revocation after quote is rechecked before signing');
  assert.equal(await client.getTransactionCount({address:accounts[4]!.address}),payerNonce);
  await assert.rejects(externalClient.purchaseTransfers(runId),/UNAUTHORIZED/);
  // Restore this test fixture only; the production API cannot un-revoke an executor.
  db.prepare('UPDATE platform_executors SET revoked=0 WHERE id=?').run(executorId);
  db.prepare('UPDATE platform_runs SET revoked=1 WHERE id=?').run(runId);
  await assert.rejects(externalClient.purchaseTransfers(runId),/GRANT_EXPIRED/);
  db.prepare('UPDATE platform_runs SET revoked=0 WHERE id=?').run(runId);
  const purchased=await externalClient.purchaseTransfers(runId);
  const repeats=await Promise.all([externalClient.purchaseTransfers(runId),externalClient.purchaseTransfers(runId)]);assert(repeats.every(value=>hashJson(value)===hashJson(purchased)));
  assert.equal(await client.getTransactionCount({address:accounts[4]!.address}),payerNonce+1,'external concurrent retries pay once');
  await assert.rejects(externalClient.upload(runId,{...purchased,output:{eventCount:'999999',totalAmountBaseUnits:'0'}}),/MPP_RESULT_MISMATCH/);
  await assert.rejects(externalClient.upload(runId,{...purchased,artifacts:[{uri:'https://attacker.test'}]}),/INVALID_INPUT/);
  const uploaded=await externalClient.upload(runId,purchased);assert.equal((await externalClient.upload(runId,purchased)).hash,uploaded.hash);
  const published=JSON.parse(String(db.prepare('SELECT body FROM objects WHERE hash=?').get(uploaded.hash)!.body));
  assert.equal(published.agentRef,undefined,'unregistered external worker never borrows the platform identity');
  assert.equal(published.artifacts.length,1);assert.equal(published.artifacts[0].mediaType,'application/vnd.worknet.tool-purchase+json');
  assert.equal((await verifyPlatformResult(externalSpec,published,config,env)).verdict,'accept');
  await assert.rejects(externalClient.purchaseTransfers(runId),/MPP_TASK_INACTIVE/,'fixed deliveries cannot initiate new tool work');
  db.prepare('UPDATE platform_runs SET executor_id=NULL WHERE id=?').run(runId);
  await assert.rejects(externalClient.upload(runId,purchased),/NOT_FOUND/,'detached executor cannot restore results');
  const takenOver=await getRun(env,runId);assert(takenOver);
  assert.equal((await storeTakerExecution(env,takenOver,purchased)).hash,uploaded.hash,'Owner takeover retains the exact saved purchase evidence');
  await receipt(await wallets[6]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'submitResult',args:[2n,1n,uploaded.hash,uploaded.uri]}));
  await receipt(await wallets[3]!.writeContract({address:manager,abi:taskManagerAbi,functionName:'acceptResult',args:[2n,1n,uploaded.hash]}));
  assert.equal(await client.readContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[accounts[6]!.address]}),50000n);
  assert.equal(await client.readContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[accounts[5]!.address]}),2000n);
  const snap=await resolveAgent(createPublicClient({chain:monadTestnet,transport:http(config.rpcUrl)}),ref,[registry]);assert.equal(snap.agentWallet,accounts[5]!.address);
  await assert.rejects(verifyWorkerBinding(createPublicClient({chain:monadTestnet,transport:http(config.rpcUrl)}),ref,accounts[3]!.address,[registry]),/WALLET_MISMATCH/);
  await receipt(await wallets[0]!.writeContract({address:registry,abi:artifact.abi,functionName:'clearWallet'}));
  await assert.rejects(resolveAgent(createPublicClient({chain:monadTestnet,transport:http(config.rpcUrl)}),ref,[registry]),/WALLET_UNBOUND/);
 } finally {globalThis.fetch=nativeFetch;node.kill('SIGTERM');db.close();}
});
