// Generated by scripts/generate-contracts.mjs. Do not edit.
export const taskManagerAbi = [
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "expected",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "actual",
        "type": "uint64"
      }
    ],
    "name": "AttemptMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DeadlineNotReached",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DeadlineReached",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "IncorrectTokenAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidParameters",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "enum TaskTypes.Status",
        "name": "actual",
        "type": "uint8"
      }
    ],
    "name": "InvalidState",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAssignedWorker",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRequester",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      }
    ],
    "name": "RequestIdConflict",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ResultHashMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "TaskNotFound",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "worker",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "attempt",
        "type": "uint64"
      }
    ],
    "name": "ClaimReleased",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "worker",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "attempt",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "reasonHash",
        "type": "bytes32"
      }
    ],
    "name": "ResultRejected",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "worker",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "attempt",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "resultURI",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "submittedAt",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "reviewDeadline",
        "type": "uint64"
      }
    ],
    "name": "ResultSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "requester",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "refundedAmount",
        "type": "uint128"
      }
    ],
    "name": "TaskCancelled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "worker",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "attempt",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "leaseExpiresAt",
        "type": "uint64"
      }
    ],
    "name": "TaskClaimed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "requester",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "operator",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "capabilityId",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "specHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "specURI",
            "type": "string"
          },
          {
            "internalType": "uint128",
            "name": "rewardAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "taskDeadline",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "claimLeaseSeconds",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "reviewWindowSeconds",
            "type": "uint32"
          }
        ],
        "indexed": false,
        "internalType": "struct TaskTypes.CreateTaskParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "name": "TaskCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "requester",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "refundedAmount",
        "type": "uint128"
      }
    ],
    "name": "TaskExpired",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "previousAttempt",
        "type": "uint64"
      }
    ],
    "name": "TaskReopened",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "requester",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "worker",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "attempt",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "amount",
        "type": "uint128"
      },
      {
        "indexed": false,
        "internalType": "enum TaskTypes.SettlementReason",
        "name": "reason",
        "type": "uint8"
      }
    ],
    "name": "TaskSettled",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "expectedAttempt",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "expectedResultHash",
        "type": "bytes32"
      }
    ],
    "name": "acceptResult",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "cancelTask",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "claimTask",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "attempt",
        "type": "uint64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "capabilityId",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "specHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "specURI",
            "type": "string"
          },
          {
            "internalType": "uint128",
            "name": "rewardAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "taskDeadline",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "claimLeaseSeconds",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "reviewWindowSeconds",
            "type": "uint32"
          }
        ],
        "internalType": "struct TaskTypes.CreateTaskParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "name": "createTask",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "expireTask",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "finalize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "requester",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      }
    ],
    "name": "getRequestParamsHash",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "getTask",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "requester",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "operator",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "worker",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "rewardAmount",
            "type": "uint128"
          },
          {
            "internalType": "bytes32",
            "name": "capabilityId",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "specHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "specURI",
            "type": "string"
          },
          {
            "internalType": "uint64",
            "name": "taskDeadline",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "claimLeaseSeconds",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "reviewWindowSeconds",
            "type": "uint32"
          },
          {
            "internalType": "uint64",
            "name": "attempt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "claimLeaseExpiresAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "submittedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "reviewDeadline",
            "type": "uint64"
          },
          {
            "internalType": "bytes32",
            "name": "resultHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "resultURI",
            "type": "string"
          },
          {
            "internalType": "enum TaskTypes.Status",
            "name": "status",
            "type": "uint8"
          }
        ],
        "internalType": "struct TaskTypes.Task",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "requester",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      }
    ],
    "name": "getTaskByRequestId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "expectedAttempt",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "expectedResultHash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "reasonHash",
        "type": "bytes32"
      }
    ],
    "name": "rejectResult",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "releaseExpiredClaim",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "settlementToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "expectedAttempt",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "resultURI",
        "type": "string"
      }
    ],
    "name": "submitResult",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalEscrowed",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
export const requesterVaultAbi = [
  {
    "inputs": [],
    "name": "InvalidAuthorization",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTaskAuthority",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      }
    ],
    "name": "RequestIdConflict",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RewardExceedsLimit",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SessionBudgetExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SessionTooShort",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedAgent",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VaultPaused",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "epoch",
        "type": "uint64"
      },
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "validAfter",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "validUntil",
            "type": "uint64"
          },
          {
            "internalType": "uint128",
            "name": "maxPerTask",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "maxTotalCommitment",
            "type": "uint128"
          }
        ],
        "indexed": false,
        "internalType": "struct TaskTypes.AuthorizationParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "name": "AgentAuthorized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "epoch",
        "type": "uint64"
      }
    ],
    "name": "AgentRevoked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Deposited",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "PausedChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "operator",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "epoch",
        "type": "uint64"
      }
    ],
    "name": "TaskAuthorityRecorded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Withdrawn",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "expectedAttempt",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "expectedResultHash",
        "type": "bytes32"
      }
    ],
    "name": "acceptResult",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "validAfter",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "validUntil",
            "type": "uint64"
          },
          {
            "internalType": "uint128",
            "name": "maxPerTask",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "maxTotalCommitment",
            "type": "uint128"
          }
        ],
        "internalType": "struct TaskTypes.AuthorizationParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "name": "authorizeAgent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "cancelTask",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "clientRequestId",
        "type": "bytes32"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "capabilityId",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "specHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "specURI",
            "type": "string"
          },
          {
            "internalType": "uint128",
            "name": "rewardAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "taskDeadline",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "claimLeaseSeconds",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "reviewWindowSeconds",
            "type": "uint32"
          }
        ],
        "internalType": "struct TaskTypes.CreateTaskParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "name": "createTask",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "getAuthorization",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          },
          {
            "internalType": "uint64",
            "name": "epoch",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "validAfter",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "validUntil",
            "type": "uint64"
          },
          {
            "internalType": "uint128",
            "name": "maxPerTask",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "maxTotalCommitment",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "committed",
            "type": "uint128"
          }
        ],
        "internalType": "struct TaskTypes.AgentAuthorization",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      }
    ],
    "name": "getTaskAuthority",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "operator",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "epoch",
            "type": "uint64"
          }
        ],
        "internalType": "struct TaskTypes.TaskAuthority",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taskId",
        "type": "uint256"
      },
      {
        "internalType": "uint64",
        "name": "expectedAttempt",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "expectedResultHash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "reasonHash",
        "type": "bytes32"
      }
    ],
    "name": "rejectResult",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "revokeAgent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "value",
        "type": "bool"
      }
    ],
    "name": "setPaused",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "settlementToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "taskManager",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
