import { useToast } from './Toast';
import {t as tr,locale} from './i18n';
import React,{useEffect,useRef,useState} from 'react';
import {visiblePolling} from './polling';
type Item={id:string;kind:'goal'|'run';targetId:string;taskId?:string;title:string;message:string;read:boolean};
export function ActivityPanel({owner,onOpen}:{owner:string;onOpen:(kind:'goal'|'run',id:string)=>void}){
 const toast=useToast();
 const [items,setItems]=useState<Item[]>([]);const [open,setOpen]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const button=useRef<HTMLButtonElement>(null);const mounted=useRef(true);
 async function load(){const r=await fetch('/platform/activity',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('通知暂未同步，请重试。');const data=await r.json();if(mounted.current){setItems(data.items);setError('');}}
 useEffect(()=>{mounted.current=true;const stop=visiblePolling(load,()=>60000,e=>{if(mounted.current)setError((e as Error).message);});return()=>{mounted.current=false;stop();};},[owner]);
 async function read(list:Item[]){setBusy(true);try{const r=await fetch('/platform/activity/read',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids:list.map(i=>i.id)})});if(!r.ok)throw new Error('已读状态未保存，请重试。');if(mounted.current)setItems(current=>current.map(i=>list.some(s=>s.id===i.id)?{...i,read:true}:i));}catch(e){if(mounted.current)toast.error((e as Error).message);}finally{if(mounted.current)setBusy(false);}}
 const unread=items.filter(i=>!i.read).length;
 return <div className="activity-anchor"><button ref={button} className="button subtle" aria-expanded={open} aria-controls="platform-activity" onClick={()=>{setOpen(!open);if(!open)void load().catch(e=>setError(e.message));}}>{tr("通知")}{unread?` · ${unread}`:''}</button>{open&&<section id="platform-activity" className="activity-panel" aria-label={tr("站内状态通知")} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);button.current?.focus();}}}><div className="section-heading"><h2>{tr("状态通知")}</h2><button className="text-button" onClick={()=>{setOpen(false);button.current?.focus();}}>{tr("关闭")}</button></div><p className="taker-explanation">{tr("最近各 60 个发布任务与接单的当前状态；离线时不推送，打开平台后同步。")}</p>{error&&<p role="alert">{tr(error)} <button className="text-button" onClick={()=>void load().catch(e=>setError(e.message))}>{tr("重新同步")}</button></p>}<div className="platform-actions"><span role="status" aria-atomic="true">{unread}{tr("条未读状态")}</span><button className="text-button" disabled={!unread||busy} onClick={()=>void read(items.filter(i=>!i.read))}>{tr("全部标为已读")}</button></div>{items.map(item=><article className="activity-item" key={item.id}><span className="pill">{item.kind==='goal'?tr("我发布的"):tr("我的接单")} · {item.read?tr("已读"):tr("未读")}</span><h3>{item.title}</h3><p>{tr(item.message)}</p><button className="button subtle" onClick={()=>{void read([item]);onOpen(item.kind,item.targetId);setOpen(false);}}>{tr("查看任务")}{item.taskId?` #${item.taskId}`:''}</button></article>)}{!items.length&&!error&&<p>{tr("暂无需要提醒的状态。你仍可在任务列表查看全部进度。")}</p>}</section>}</div>;
}
