import { PrivateDelivery } from './PrivateDelivery';
import { isPrivateOutput } from '@agent-task/privacy';
import {t as tr,locale} from './i18n';
import React from 'react';
import {formatUnits} from 'viem';
import {Money,short} from './components';

type Hosted = {status:string;agentName:string;message:string;metrics:{modelRequests:number;toolQueries:number;executionTries:number};costs:{serviceFeeBaseUnits:string;gasPayer:string;confirmedGasWei:string|null;gasTransactions:Array<{hash:string;paidWei:string;payer:string}>};logs:Array<{at:string;stage:string;message:string}>};
export const hostedStatus=(status:string)=>({waiting_authorization:'等待授权',waiting_claim:'等待领取',running:'云端执行中',ready:'待钱包提交',submitting:'提交确认中',reviewing:'独立审核中',completed:'已验证交付',settled_unverified:'已结算，待核对',settled_scored:'已按完成度结算',stopped:'已停止',failed:'执行未完成',expired:'本轮已结束',rejected:'审核未通过'}[status]??'准备中');
const sourceHref=(value:string)=>{try{const url=new URL(value);return url.protocol==='https:'?url.href:undefined;}catch{return undefined;}};
export function HostedExecution({job,modelUsage,result,owner,mode,canSubmit,busy,onSubmit}:{job:Hosted;modelUsage?:Array<{stage:string;provider:string;model:string;requests:number;succeeded:number;inputTokens:number|null;outputTokens:number|null;unknownUsage:number}>;result:any;owner:string;mode:string;canSubmit:boolean;busy:boolean;onSubmit:()=>void}){
 return <section className="hosted-execution" aria-label={tr("平台托管执行")}><div className="section-heading"><h3>{tr(job.agentName)}</h3><span className="pill">{tr(hostedStatus(job.status))}</span></div><p className="hosted-status" role="status">{tr(job.message)}</p>
 <div className="taker-terms hosted-usage"><div>{tr("执行服务费")}<strong><Money amount={job.costs.serviceFeeBaseUnits}/> test USDC</strong><small>{tr("测试期间由平台承担算力成本")}</small></div><div>{tr("资源用量")}<strong>{tr("生成请求尝试")}{job.metrics.modelRequests}{tr("次")}</strong><small>{tr("工具查询")}{job.metrics.toolQueries}{tr("次 · 执行尝试")}{job.metrics.executionTries}/2</small></div><div>{tr("已确认交易 gas")}<strong>{job.costs.confirmedGasWei===null?tr("等待链上记录"):`${formatUnits(BigInt(job.costs.confirmedGasWei),18)} MON`}</strong><small>{job.costs.gasPayer==='platform'?tr("平台支付"):job.costs.gasPayer==='mixed'?tr("多个账户分别支付"):tr("你的钱包支付")} · {job.costs.gasTransactions.length}{tr("笔已核对")}</small></div></div>
 <p className="taker-explanation">{tr("报酬接收账户：")}{short(owner)}{tr("。生成与审核分别记录，包含失败及中断尝试；此处不推算平台的美元账单。已确认 gas 可能尚未包含仍在确认的交易。")}</p>
 {result&&isPrivateOutput(result.output)?<PrivateDelivery result={result}/>:result&&<article className="deliverable hosted-deliverable"><div className="deliverable-head"><h3>{tr("本轮交付")}</h3><span className="pill">{job.status==='completed'?tr("独立审核通过"):tr("以审核与链上记录为准")}</span></div><div className="result-document">{result.output?.mode==='llm'?<><p className="research-summary">{result.output.summary}</p>{result.output.findings?.map((finding:any,index:number)=><section className="finding" key={index}><h3>{finding.title}</h3><p>{finding.claim}</p><blockquote>{finding.quote}</blockquote><a href={sourceHref(finding.sourceUri)} target="_blank" rel="noreferrer">{tr("查看来源")}</a></section>)}</>:<div className="analysis-result"><div><span>{tr("转账次数")}</span><strong>{result.output?.eventCount}</strong></div><div><span>{tr("转账总额")}</span><strong><Money amount={result.output?.totalAmountBaseUnits}/><small>test USDC</small></strong></div></div>}</div></article>}
 {canSubmit&&mode==='wallet'&&<div className="platform-actions"><button className="button primary" disabled={busy} onClick={onSubmit}>{tr("确认交付并用钱包提交")}</button><span className="taker-explanation">{tr("须在本轮提交截止前确认")}</span></div>}
 {modelUsage&&modelUsage.length>0&&<details><summary>{tr("生成与审核用量")}</summary>{modelUsage.map((entry,index)=><p key={index}>{entry.stage==='generation'?tr("交付生成"):entry.stage==='quotation-review'?tr("引文审核"):tr("整体审核")} · {entry.provider} / {entry.model}<br/>{entry.requests}{tr("次请求 ·")}{entry.succeeded}{tr("次成功 · 输入")}{entry.inputTokens??tr("未知")}{tr("/ 输出")}{entry.outputTokens??tr("未知")} tokens{entry.unknownUsage>0?tr("（部分用量未返回，未按零计）"):''}</p>)}</details>}
 {job.costs.gasTransactions.length>0&&<details><summary>{tr("交易费用记录")}</summary>{job.costs.gasTransactions.map(tx=><p key={tx.hash}>{formatUnits(BigInt(tx.paidWei),18)}{tr("MON · 支付账户")}{short(tx.payer)} <a href={`https://testnet.monadexplorer.com/tx/${tx.hash}`} target="_blank" rel="noreferrer">{tr("查看交易")}</a></p>)}</details>}
 <details><summary>{tr("运行记录（")}{job.logs.length}）</summary><ol className="hosted-log">{job.logs.map((entry,index)=><li key={`${entry.at}:${index}`}><time dateTime={entry.at}>{new Date(entry.at).toLocaleTimeString(locale())}</time><span>{tr(entry.message)}</span></li>)}</ol></details>
 <p className="taker-explanation">{tr("停止托管执行会阻断后续上传和提交；已发起的推理可能仍消耗平台资源。停止计算不会立即释放链上领取，已签名或上链交易也不能撤回。")}</p>
 </section>;
}
